export const GET_ASSISTANTS = 'GET_ASSISTANTS';
export const ADD_ASSISTANT = 'ADD_ASSISTANT';
export const UPDATE_ASSISTANT = 'UPDATE_ASSISTANT';
export const GET_SUITES = 'GET_SUITES';
export const ADD_SUITE = 'ADD_SUITE';
export const UPDATE_SUITE = 'UPDATE_SUITE';
export const SET_ERROR = 'SET_ERROR';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const ASSISTANT_LOADING = 'ASSISTANT_LOADING';

